### PR TITLE
MP OpenAPI fraction refactoring

### PR DESCRIPTION
**Pull request by mkouba**
I'd rather do a PR as the changeset is rather large. With these changes I was able to pass the real tck (to run it just `mvn clean test` in `/testsuite/microprofile-tcks/openapi`).

Few notes:
* I changed some package names and move some classes - this is due to how swarm builds modules for a fraction; if needed I can try to explain what I know about this
* the api/tck version is defined in `build-parent/pom.xml` -> we should update to 1.0.1 once it's released
* your unit tests/tck runner work as before
* the model init is now split into `OpenApiDeploymentProcessor` and `OpenApiServletContextListener`
* in `OpenApiSerializer.serialize(OpenAPI, Format)` I enabled `YAMLGenerator.Feature.ALWAYS_QUOTE_NUMBERS_AS_STRINGS` to pass the tck (note that tck converts YAML to JSON before assertions are made)
* maybe I will add more when I remember...

The current state is probably not ideal but we can always improve ;-)

### CODE REVIEW

**Comment by EricWittmann** [comment]
Thanks @mkouba  - I'll review ASAP.  No later than Monday. :)

**Comment by msavy** [comment]
> in OpenApiSerializer.serialize(OpenAPI, Format) I enabled YAMLGenerator.Feature.ALWAYS_QUOTE_NUMBERS_AS_STRINGS to pass the tck (note that tck converts YAML to JSON before assertions are made)


Hmm, always quoting numbers as strings kinda sounds like there's a bug with the TCK. Unless this is referring to string fields that coincidentally have a number in them?

**Comment by mkouba** [comment]
`ALWAYS_QUOTE_NUMBERS_AS_STRINGS` javadoc: _Whether numbers stored as strings will be rendered with quotes (true) or without quotes (false, default) when MINIMIZE_QUOTES is enabled._

**Comment by mkouba** [comment]
Cool! Let me know if you have any other problems...

**Pull request merged**
